id: node.search_result
uuid: 31037c9e-5a56-418c-a307-7b296ea7176c
label: 'Search result highlighting input'
targetEntityType: node
status: false
cache: true
langcode: und
dependencies:
  module:
    - node
